---
- name: Démonstration des commandes Cisco IOS
  hosts: routers
  gather_facts: no

  tasks:
    - name: Exécuter les commandes show
      cisco.ios.ios_command:
        commands:
          - show run
          - show ip int brief
      register: sh_outputs

    - debug:
        msg: "{{ sh_outputs.stdout_lines }}"

    - name: Vérifier les conditions
      cisco.ios.ios_command:
        commands:
          - show run
          - show ip int brief
        match: any
        wait_for:
          - result[0] contains "description connected to core"
          - result[1] contains "ethernet0/1"
