---
- name: Afficher les interfaces sur Cisco IOS
  hosts: 192.168.96.138
  gather_facts: no

  tasks:
    - name: Exécuter la commande show ip interface brief
      cisco.ios.ios_command:
        commands:
          - show ip interface brief
      register: interface_output

    - debug:
        msg: "{{ interface_output.stdout_lines }}"
